name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        working-directory: app
        run: npm install
      - name: Syntax check
        working-directory: app
        run: npm test

  validate-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt check
        working-directory: infra
        run: terraform fmt -check
      - name: Terraform init
        working-directory: infra
        run: terraform init -backend=false
      - name: Terraform validate
        working-directory: infra
        run: terraform validate
