name: Build AMI (Packer)

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "packer/**"
  workflow_dispatch: {}

jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - uses: hashicorp/setup-packer@main

      - name: Packer init
        working-directory: packer
        run: packer init pulsewatch.pkr.hcl

      - name: Packer build
        working-directory: packer
        run: packer build pulsewatch.pkr.hcl
